# Generated by Django 4.1.2 on 2024-01-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0012_alter_user_participated_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
