# Generated by Django 4.1.2 on 2024-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0013_games_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='image',
            field=models.ImageField(null=True, upload_to='main_event_images'),
        ),
    ]
